# Generated by Django 5.1.5 on 2025-03-01 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playground', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Song', max_length=50)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='saved_covers/')),
                ('audio', models.FileField(upload_to='saved_audio/')),
                ('video', models.FileField(blank=True, null=True, upload_to='saved_videos/')),
                ('author', models.CharField(default='Unknow', max_length=50)),
                ('original_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.song')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_songs', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_songs', to='saved.userprofile')),
            ],
        ),
    ]
