# Generated by Django 5.1.5 on 2026-05-09 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saved', '0002_alter_savedsong_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedsong',
            name='author',
        ),
    ]
