# Generated by Django 5.1.5 on 2025-03-01 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('audio', models.FileField(upload_to='songs/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('tags', models.CharField(choices=[('none', 'None'), ('pop', 'Pop'), ('modern', 'Modern'), ('rock', 'Rock'), ('hip-hop', 'Hip-Hop'), ('rap', 'Rap'), ('jazz', 'Jazz'), ('electronic', 'Electronic'), ('anime', 'Anime'), ('classic', 'Classic'), ('video', 'Video')], default='none', max_length=100)),
                ('author', models.CharField(default='Unknown', max_length=70)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='albums.album')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_songs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
