# Generated by Django 5.1.5 on 2026-05-09 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='author',
        ),
    ]
